// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa9UeF8rRq-QrmXg0I4fSA5LawPYfz2Ps',
    appId: '1:1036001299428:web:9ccf1e70836af1574c15f1',
    messagingSenderId: '1036001299428',
    projectId: 'cash-planner-62c59',
    authDomain: 'cash-planner-62c59.firebaseapp.com',
    storageBucket: 'cash-planner-62c59.firebasestorage.app',
    measurementId: 'G-VXJ6TKE7LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM_RvnziccmuAQva9RBMSt3_VMFKH_bAQ',
    appId: '1:1036001299428:android:b32076df167246914c15f1',
    messagingSenderId: '1036001299428',
    projectId: 'cash-planner-62c59',
    storageBucket: 'cash-planner-62c59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEEkOzjI4ZP3B-_As1SOBR3KHVDJe2Q1Q',
    appId: '1:1036001299428:ios:1bf27368123a80bc4c15f1',
    messagingSenderId: '1036001299428',
    projectId: 'cash-planner-62c59',
    storageBucket: 'cash-planner-62c59.firebasestorage.app',
    iosBundleId: 'com.example.cashPlannerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEEkOzjI4ZP3B-_As1SOBR3KHVDJe2Q1Q',
    appId: '1:1036001299428:ios:1bf27368123a80bc4c15f1',
    messagingSenderId: '1036001299428',
    projectId: 'cash-planner-62c59',
    storageBucket: 'cash-planner-62c59.firebasestorage.app',
    iosBundleId: 'com.example.cashPlannerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa9UeF8rRq-QrmXg0I4fSA5LawPYfz2Ps',
    appId: '1:1036001299428:web:3abbf2e8cc5e57fe4c15f1',
    messagingSenderId: '1036001299428',
    projectId: 'cash-planner-62c59',
    authDomain: 'cash-planner-62c59.firebaseapp.com',
    storageBucket: 'cash-planner-62c59.firebasestorage.app',
    measurementId: 'G-9GQWHMC4WZ',
  );

}